export const PrismaErrors = {
	CONFLICT: {
		P2002: 'Duplicate entry: A record with this value already exists.',
		P2003: 'Foreign key error: Referenced record not found.',
		P2004: 'Integrity issue: A database rule was violated.',
		P2011: 'Null value error: A required field cannot be null.',
		P2014: 'Relationship error: Action would break a required relationship.',
	},
	NOT_FOUND: {
		P2001: "Record not found: The specified record doesn't exist.",
		P2015: 'Related record not found: A linked record is missing.',
		P2018: 'Required connection missing: Related records not found.',
		P2021: 'Table not found: The specified table does not exist.',
		P2022: 'Column not found: The specified column does not exist.',
	},
	BAD_REQUEST: {
		P2000: 'Value too long: Exceeds allowed column length.',
		P2005: 'Invalid data type: Stored value is incorrect.',
		P2006: 'Invalid input: Value does not match the field format.',
		P2007: "Validation error: Provided data doesn't meet requirements.",
		P2008: 'Syntax error: The query is not correctly formatted.',
		P2009: 'Query error: Failed validation check.',
		P2010: 'Query execution failed: Check the raw query.',
		P2012: 'Missing value: A required field was not provided.',
		P2013: 'Missing argument: Required argument is missing in function.',
		P2016: "Query error: Couldn't interpret the query.",
		P2017: 'Relationship issue: Parent-child records are not connected.',
		P2019: 'Invalid input: Provided value is incorrect.',
		P2023: 'Inconsistent data: Issues found in column data.',
		P2025: 'Missing dependency: Operation failed due to missing records.',
		P2026: "Unsupported feature: The current database doesn't support this feature.",
		P2027: 'Multiple issues: Several errors occurred during query.',
		P2028: 'Transaction error: API issue with transaction.',
		P2029: 'Parameter limit exceeded: Too many query parameters.',
		P2030: 'Fulltext index missing: Add @@fulltext([Fields...]) to schema.',
		P2031: 'Replica set required: MongoDB must run as a replica set for transactions.',
		P2033: 'Number too large: Use BigInt for very large numbers.',
		P2034: 'Transaction failed: Write conflict or deadlock occurred.',
		P2035: 'Database error: Assertion failed on the database side.',
		P2036: 'External error: Issue with an external connector.',
		P2037: 'Too many connections: Database connection limit exceeded.',
	},
};
